# -*- coding: utf-8 -*-
"""My CNN traing ver. 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Y84Cd2w7JDPykipEsgML19dqNWhpQDK

**CELL 1** — Imports libraries, Decides configuration and Defines utility Functions
"""

import os
import shutil
from pathlib import Path

import numpy as np
import tensorflow as tf

# Device Information

print("="*60)
print(f"TensorFlow Version : {tf.__version__}")

if tf.config.list_physical_devices('GPU'):
    print("Running on GPU")
else:
    print("Running on CPU")

print("="*60)

# Dataset Parameters

IMAGE_SIZE = 16 # Desired Size of input images
NUM_CLASSES = 3 # Number of classified classes

# CNN Parameters

NUM_FILTERS = 2 # No. of Convolution Filters
KERNEL_SIZE = 3 # Size of kernel is 3x3
POOL_SIZE = 2 # Size of Max-Pooling matrices (2x2)

# Fixed Point Formats
#
# Total bits = Sign + Integer + Fraction
#
# Example:
#
# Weight Integer = 3
# Weight Fraction = 8
#
# gives Q3.8
# (12 bits total)
#

# Pixel Data
PIXEL_BITS = 8
PIXEL_SIGNED = False

# Convolution Weights
WEIGHT_INT_BITS = 3
WEIGHT_FRAC_BITS = 8

# Convolution Biases
BIAS_INT_BITS = 3
BIAS_FRAC_BITS = 8

# Convolution / ReLU / Pool Outputs
CONV_OUTPUT_BITS = 24

# Final Dense Neuron Output
NEURON_OUTPUT_BITS = 44

# Training Parameters

LEARNING_RATE = 0.005
BATCH_SIZE = 64
EPOCHS = 20

# Derived Constants

WEIGHT_TOTAL_BITS = 1 + WEIGHT_INT_BITS + WEIGHT_FRAC_BITS #Q3.8 is 11 bits, 12th bit is for sign
BIAS_TOTAL_BITS = 1 + BIAS_INT_BITS + BIAS_FRAC_BITS

WEIGHT_SCALE = 1 << WEIGHT_FRAC_BITS # indicate bit 1 left shifted as many times reqd.
BIAS_SCALE = 1 << BIAS_FRAC_BITS

# Signed integer range representable by each Q-format (two's complement).
# e.g. for Q3.8 (12 bits total): -2048 .. 2047
WEIGHT_INT_MIN = -(1 << (WEIGHT_TOTAL_BITS - 1))
WEIGHT_INT_MAX = (1 << (WEIGHT_TOTAL_BITS - 1)) - 1

BIAS_INT_MIN = -(1 << (BIAS_TOTAL_BITS - 1))
BIAS_INT_MAX = (1 << (BIAS_TOTAL_BITS - 1)) - 1

IMAGE_PIXELS = IMAGE_SIZE * IMAGE_SIZE

CONV_OUTPUT_SIZE = IMAGE_SIZE - KERNEL_SIZE + 1
POOL_OUTPUT_SIZE = CONV_OUTPUT_SIZE // 2

FEATURE_MAP_SIZE = POOL_OUTPUT_SIZE * POOL_OUTPUT_SIZE

FC_INPUTS = NUM_FILTERS * FEATURE_MAP_SIZE

print("Configuration Loaded Successfully\n")

print(f"Image Size           : {IMAGE_SIZE}x{IMAGE_SIZE}")
print(f"Feature Map Size     : {POOL_OUTPUT_SIZE}x{POOL_OUTPUT_SIZE}")
print(f"Flatten Size         : {FC_INPUTS}")

# Output Folder Structure

EXPORT_ROOT = Path("hardware_verification_files")
TEST_IMAGE_ROOT = Path("test_images_archive")

# Utility Functions

def recreate_directory(directory):
    # Deletes and recreates a directory. So that every time the code is re-run the exported folders are new.
    directory = Path(directory)
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True)


# Fixed Point Quantization
def quantize_tensor(tensor, integer_bits, fractional_bits):
    """
    Quantize TensorFlow tensor to signed fixed point.
    Example:
        integer_bits = 3
        fractional_bits = 8
        => Q3.8
    """

    scale = 2 ** fractional_bits #converts tensor from decimal to integer by multiplying with 2^(no. of frac. bits)
    total_bits = 1 + integer_bits + fractional_bits
    min_val = -(2 ** (total_bits - 1)) / scale
    max_val = ((2 ** (total_bits - 1)) - 1) / scale

    tensor = tf.round(tensor * scale)
    tensor = tf.clip_by_value( tensor, min_val * scale, max_val * scale )

    tensor = tensor / scale
    return tensor


# Float -> Fixed Integer
def float_to_fixed(value, fractional_bits):
    #Converts float to fixed-point integer.
    return int(np.round(value * (2 ** fractional_bits)))

# Two's Complement Conversion
def int_to_twos_complement(value, bits):
    #Converts signed integer to binary string.
    value = int(value)
    if value < 0:
        value = (1 << bits) + value
    value &= (1 << bits) - 1

    return format(value, f"0{bits}b")


# Binary File Writer
def write_binary_file(filename, values, bits):
    #Writes iterable of integers into .mem file.
    with open(filename, "w") as f:
        for value in values:
            f.write(int_to_twos_complement(value, bits))
            f.write("\n")

# Decimal File Writer
def write_decimal_file(filename, values):
    np.savetxt(filename, values, fmt="%d")

# Image Export
def export_image(image, filename):
    image = np.asarray(image).astype(np.uint8)

    with open(filename, "w") as f:
        for pixel in image.flatten():
            f.write(format(int(pixel), "08b"))
            f.write("\n")


# Overflow Checker
def check_overflow(values, bits, name="Value"):

    minimum = -(1 << (bits - 1))
    maximum = (1 << (bits - 1)) - 1

    values = np.asarray(values)

    if np.any(values < minimum):
        print(f"WARNING: {name} underflow detected.")

    if np.any(values > maximum):
        print(f"WARNING: {name} overflow detected.")


# Dense Weight Reordering
def reorder_dense_weights(fc_weights,
                          num_feature_maps=NUM_FILTERS,
                          feature_map_size=FEATURE_MAP_SIZE):
    """
    Reorders Dense weights so that each neuron receives
        Feature Map 0
        then
        Feature Map 1
    exactly matching neuron module

    Input from Keras
        (98,3)
    Returned:
        (98,3)
    with ordering
        FM0[49]
        FM1[49]
    """

    num_neurons = fc_weights.shape[1]

    reordered = (
        fc_weights.reshape(feature_map_size, num_feature_maps, num_neurons)
        .transpose(1, 0, 2)
        .reshape(feature_map_size * num_feature_maps, num_neurons) )

    return reordered

print("\nUtility Functions Loaded Successfully.")



"""**Cell 2:** Load MNIST Dataset and preprocess images"""

print("Loading MNIST dataset...")

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

def preprocess_labels(labels):
    #Convert labels into: 1)0 -> 0; 2)1 -> 1; 3)2-9 -> 2
    return np.where(labels > 1, 2, labels).astype(np.int32)

def preprocess_images(images):
    """
    Resize images and normalize to [0,1].

    Output format:
        (N, IMAGE_SIZE, IMAGE_SIZE, 1)   # NHWC
    """
    images = np.expand_dims(images, axis=-1)
    images = tf.image.resize( images, (IMAGE_SIZE, IMAGE_SIZE) ).numpy()
    images = images.astype(np.float32) / 255.0
    return images

x_train = preprocess_images(x_train)
x_test = preprocess_images(x_test)

y_train = preprocess_labels(y_train)
y_test = preprocess_labels(y_test)

print(f"Training Images : {len(x_train)}")
print(f"Testing Images  : {len(x_test)}")

unique, counts = np.unique(y_train, return_counts=True)

print("\nTraining Distribution")
for label, count in zip(unique, counts):
    print(f"Class {label}: {count}")

print("\nImage Tensor Shape :", x_train.shape)
print("Label Tensor Shape :", y_train.shape)

assert x_train.shape[1] == IMAGE_SIZE
assert x_train.shape[2] == IMAGE_SIZE
assert x_train.shape[3] == 1

assert FC_INPUTS == NUM_FILTERS * ((IMAGE_SIZE - KERNEL_SIZE + 1) // POOL_SIZE) ** 2

print("\nDataset preprocessing completed successfully.")



"""**Cell 3:** Building the CNN"""

MAX_WEIGHT = (2 ** WEIGHT_INT_BITS) - (1 / (2 ** WEIGHT_FRAC_BITS))
MIN_WEIGHT = -(2 ** WEIGHT_INT_BITS)

MAX_BIAS = (2 ** BIAS_INT_BITS) - (1 / (2 ** BIAS_FRAC_BITS))
MIN_BIAS = -(2 ** BIAS_INT_BITS)

class ClipConstraint(tf.keras.constraints.Constraint):
    #Element-wise clip to [min_value, max_value] so quantized values stay
    #within the representable Q-format range.

    def __init__(self, min_value, max_value):
        self.min_value = min_value
        self.max_value = max_value

    def __call__(self, w):
        return tf.clip_by_value( w, clip_value_min=self.min_value,
            clip_value_max=self.max_value )

    def get_config(self):
        return {"min_value": self.min_value, "max_value": self.max_value}

weight_constraint = ClipConstraint(MIN_WEIGHT, MAX_WEIGHT)
bias_constraint = ClipConstraint(MIN_BIAS, MAX_BIAS)

class TinyCNN(tf.keras.Model):

    def __init__(self):
        super().__init__()

        self.conv = tf.keras.layers.Conv2D(
            filters=NUM_FILTERS,
            kernel_size=KERNEL_SIZE,
            strides=1,
            padding="valid",
            use_bias=True,
            kernel_constraint=weight_constraint,
            bias_constraint=bias_constraint )

        self.relu = tf.keras.layers.ReLU()

        self.pool = tf.keras.layers.MaxPooling2D(
            pool_size=POOL_SIZE,
            strides=POOL_SIZE,
            padding="valid" )

        self.flatten = tf.keras.layers.Flatten()

        self.fc = tf.keras.layers.Dense(
            NUM_CLASSES,
            use_bias=True,
            kernel_constraint=weight_constraint,
            bias_constraint=bias_constraint )

    def call(self, x):

        x = self.conv(x)
        x = self.relu(x)
        x = self.pool(x)
        x = self.flatten(x)
        x = self.fc(x)
        return x


model = TinyCNN()
model.build( input_shape=(None, IMAGE_SIZE, IMAGE_SIZE, 1))
model.summary()



"""**Cell 4:** Train and Evaluate CNN"""

print("Training Floating-Point CNN")

model.compile(
    optimizer=tf.keras.optimizers.Adam( learning_rate=LEARNING_RATE),
    loss=tf.keras.losses.SparseCategoricalCrossentropy( from_logits=True ),
    metrics=["accuracy"])

checkpoint = tf.keras.callbacks.ModelCheckpoint(
    filepath="best_model.weights.h5",
    monitor="val_accuracy",
    mode="max",
    save_best_only=True,
    save_weights_only=True,
    verbose=1 )

history = model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    shuffle=True,
    callbacks=[checkpoint],
    verbose=1 )

print("\nLoading best validation model...")

model.load_weights("best_model.weights.h5")

train_loss, train_accuracy = model.evaluate( x_train, y_train, batch_size=1000, verbose=0 )

test_loss, fp32_accuracy = model.evaluate( x_test, y_test, batch_size=1000, verbose=0 )

fp32_accuracy *= 100
train_accuracy *= 100

print("\nFloating Point Performance\n")


print(f"Training Accuracy : {train_accuracy:.2f}%")
print(f"Testing Accuracy  : {fp32_accuracy:.2f}%")
print(f"Training Loss     : {train_loss:.6f}")
print(f"Testing Loss      : {test_loss:.6f}")

predictions = model.predict( x_test[:10], verbose=0 )

predicted_classes = np.argmax(predictions, axis=1)

print("\nFirst 10 Predictions")


for i in range(10):
    print(
        f"Image {i:2d} | "
        f"Expected : {y_test[i]} | "
        f"Predicted : {predicted_classes[i]}" )

print("\nTraining completed successfully.")



"""**Cell 5:** Quantize Models and Analyze parameters"""

print("Quantizing Model")

quantized_model = TinyCNN()

_ = quantized_model(tf.convert_to_tensor(x_test[:1]))

for q_layer, fp_layer in zip(quantized_model.layers, model.layers):
    weights = fp_layer.get_weights()
    if len(weights) == 0:
        continue

    quantized_weights = []
    for idx, tensor in enumerate(weights):
        if idx == 0:
            int_bits, frac_bits = WEIGHT_INT_BITS, WEIGHT_FRAC_BITS
        else:
            int_bits, frac_bits = BIAS_INT_BITS, BIAS_FRAC_BITS

        q_tensor = quantize_tensor(
            tf.convert_to_tensor(tensor), int_bits, frac_bits ).numpy()
        quantized_weights.append(q_tensor)

    q_layer.set_weights(quantized_weights)

quantized_model.compile( loss=tf.keras.losses.SparseCategoricalCrossentropy( from_logits=True ), metrics=["accuracy"] )

q_loss, q_accuracy = quantized_model.evaluate( x_test, y_test, batch_size=1000, verbose=0 )
q_accuracy *= 100

print("\nFloating Point Accuracy : {:.2f}%".format(fp32_accuracy))
print("Quantized Accuracy      : {:.2f}%".format(q_accuracy))
print("Accuracy Loss           : {:.2f}%".format(fp32_accuracy-q_accuracy))

print("\n")
print("="*60)
print("Layer Statistics")
print("="*60)

for layer in quantized_model.layers:
    weights = layer.get_weights()
    if len(weights) == 0:
        continue
    W = weights[0]
    B = weights[1]

    print(f"\nLayer : {layer.name}")

    print(f"Weights Shape : {W.shape}")
    print(f"Bias Shape    : {B.shape}")

    print(f"Weight Min    : {W.min():.6f}")
    print(f"Weight Max    : {W.max():.6f}")

    print(f"Bias Min      : {B.min():.6f}")
    print(f"Bias Max      : {B.max():.6f}")

    weight_int = np.round(W * WEIGHT_SCALE).astype(np.int32)
    bias_int = np.round(B * BIAS_SCALE).astype(np.int32)

    check_overflow( weight_int, WEIGHT_TOTAL_BITS, f"{layer.name} Weights" )

    check_overflow( bias_int, BIAS_TOTAL_BITS, f"{layer.name} Biases" )

print("\nExtracting Quantized Parameters")

conv_weights, conv_biases = quantized_model.conv.get_weights()
fc_weights, fc_biases = quantized_model.fc.get_weights()

fc_weights = reorder_dense_weights( fc_weights, num_feature_maps=NUM_FILTERS, feature_map_size=FEATURE_MAP_SIZE )

conv_weights_int = np.clip( np.round(conv_weights * WEIGHT_SCALE), WEIGHT_INT_MIN, WEIGHT_INT_MAX ).astype(np.int32)

conv_biases_int = np.clip( np.round(conv_biases * BIAS_SCALE), BIAS_INT_MIN, BIAS_INT_MAX ).astype(np.int32)

fc_weights_int = np.clip( np.round(fc_weights * WEIGHT_SCALE), WEIGHT_INT_MIN, WEIGHT_INT_MAX ).astype(np.int32)

fc_biases_int = np.clip( np.round(fc_biases * BIAS_SCALE), BIAS_INT_MIN, BIAS_INT_MAX ).astype(np.int32)

print("Convolution Kernel Shape :", conv_weights.shape)
print("Dense Weight Shape       :", fc_weights.shape)

print("\nDense weights reordered as:")

print(f"Feature Map 0 : 0 -> {FEATURE_MAP_SIZE-1}")
print(f"Feature Map 1 : {FEATURE_MAP_SIZE} -> {FC_INPUTS-1}")

print("\nQuantization completed successfully.")



"""**Cell 5B:** Builds Hardware Parameter Package"""

print("Building Hardware Parameter Package")

hardware = {

    # Convolution Parameters
    "conv": {
        "weights_float": conv_weights,
        "weights_int": conv_weights_int,

        "bias_float": conv_biases,
        "bias_int": conv_biases_int,

        "filters": NUM_FILTERS,
        "kernel_size": KERNEL_SIZE },

    # Dense Parameters
    "dense": {
        "weights_float": fc_weights,
        "weights_int": fc_weights_int,

        "bias_float": fc_biases,
        "bias_int": fc_biases_int,

        "inputs": FC_INPUTS,
        "outputs": NUM_CLASSES },

    # Fixed Point Formats
    "format": {
        "pixel_bits": PIXEL_BITS,

        "weight_bits": WEIGHT_TOTAL_BITS,
        "weight_frac": WEIGHT_FRAC_BITS,

        "bias_bits": BIAS_TOTAL_BITS,
        "bias_frac": BIAS_FRAC_BITS,
        "conv_bits": CONV_OUTPUT_BITS,
        "neuron_bits": NEURON_OUTPUT_BITS },

    # Network Dimensions
    "network": {
        "image_size": IMAGE_SIZE,
        "conv_size": CONV_OUTPUT_SIZE,
        "pool_size": POOL_OUTPUT_SIZE,
        "flatten_size": FC_INPUTS,
        "classes": NUM_CLASSES }}

print("\nHardware package successfully created.\n")
print("Contents")

for key in hardware:
    print("  •", key)

print("\nConvolution Weight Shape")
print(hardware["conv"]["weights_int"].shape)

print("\nDense Weight Shape")
print(hardware["dense"]["weights_int"].shape)



"""**Cell 6:** Emulates the Model to give expected convolution/ReLU/MaxPooling results"""

print("Building Hardware Emulation Library")

def prepare_image(image_tensor):
    #Converts normalized tensor into unsigned 8-bit image.
    image = np.clip(
        np.round(image_tensor.squeeze() * 255),
        0, 255 ).astype(np.uint8)
    return image

def emulate_convolution(image, kernel, bias):
    """
    image  : uint8 image
    kernel : signed integer kernel
    bias   : signed integer Q-format bias

    Returns: signed accumulator output
    """

    rows = image.shape[0] - KERNEL_SIZE + 1
    cols = image.shape[1] - KERNEL_SIZE + 1

    output = np.zeros((rows, cols), dtype=np.int32)

    for r in range(rows):
        for c in range(cols):
            window = image[ r:r+KERNEL_SIZE, c:c+KERNEL_SIZE ].astype(np.int32)
            output[r, c] = np.sum(window * kernel) + bias
    return output

def emulate_relu(feature_map):
    return np.maximum(feature_map, 0)

def emulate_pool(feature_map):
    #2x2 Max Pool
    rows = feature_map.shape[0] // POOL_SIZE
    cols = feature_map.shape[1] // POOL_SIZE

    pooled = np.zeros((rows, cols), dtype=np.int32)

    for r in range(rows):
        for c in range(cols):
            pooled[r, c] = np.max( feature_map[ r*POOL_SIZE:r*POOL_SIZE+POOL_SIZE, c*POOL_SIZE:c*POOL_SIZE+POOL_SIZE ])
    return pooled


def flatten_feature_maps(feature_maps):
    #Feature Map 0 followed by Feature Map 1
    flattened = []

    for fmap in feature_maps:
        flattened.extend(fmap.flatten())
    return np.asarray(flattened, dtype=np.int32)

def emulate_dense(features, weights, bias):
    """
    features : pooled feature vector
    weights  : reordered dense weights
    bias     : signed integer bias

    Matches neuron.v
    """

    accumulator = bias << WEIGHT_FRAC_BITS
    accumulator += np.sum(features * weights)

    return int(accumulator)


def emulate_complete_pipeline(image_tensor):
    """
    Executes complete hardware pipeline.
    Returns dictionary containing every stage.
    """

    image = prepare_image(image_tensor)

    conv_maps = []
    relu_maps = []
    pool_maps = []

    for channel in range(NUM_FILTERS):

        kernel = hardware["conv"]["weights_int"][:,:,0,channel]
        bias = hardware["conv"]["bias_int"][channel]
        conv = emulate_convolution( image, kernel, bias )

        relu = emulate_relu(conv)

        pool = emulate_pool(relu)

        conv_maps.append(conv)
        relu_maps.append(relu)
        pool_maps.append(pool)

    flattened = flatten_feature_maps(pool_maps)

    neuron_outputs = []

    for neuron in range(NUM_CLASSES):
        neuron_outputs.append(
            emulate_dense( flattened, hardware["dense"]["weights_int"][:, neuron], hardware["dense"]["bias_int"][neuron] ))

    prediction = int(np.argmax(neuron_outputs))
    return {
        "image": image,
        "conv": conv_maps,
        "relu": relu_maps,
        "pool": pool_maps,
        "flatten": flattened,
        "neurons": neuron_outputs,
        "prediction": prediction }


print("Testing pipeline...")

test_result = emulate_complete_pipeline(x_test[0])

print("Pipeline OK")

print(f"Image Shape      : {test_result['image'].shape}")
print(f"Conv Shape       : {test_result['conv'][0].shape}")
print(f"Pool Shape       : {test_result['pool'][0].shape}")
print(f"Flatten Length   : {len(test_result['flatten'])}")
print(f"Neuron Outputs   : {test_result['neurons']}")
print(f"Prediction       : {test_result['prediction']}")
print("\nHardware emulation library ready.")



"""**Cell 7:** Defining Export functions"""

print("Initializing Export Manager")

# Directory Utilities

def create_clean_folder(folder):
    folder = Path(folder)

    if folder.exists():
        shutil.rmtree(folder)
    folder.mkdir(parents=True)

def create_folder(folder):
    folder = Path(folder)
    folder.mkdir(parents=True, exist_ok=True)

# Generic Export Utilities

def export_binary(filename, values, bits):
    values = np.asarray(values).flatten()
    write_binary_file( filename, values, bits )

def export_decimal(filename, values):
    values = np.asarray(values).flatten()
    write_decimal_file( filename, values )

# Indexed Parameter Export

def export_indexed_parameters(filename, values, bits, parameter_type="generic"):
    values = np.asarray(values).flatten()

    with open(filename, "w") as f:
        if parameter_type == "kernel":
            f.write( "Index\tRow\tCol\tDecimal\tBinary\n")
            f.write( "-"*70 + "\n")

            for idx, value in enumerate(values):
                row = idx // KERNEL_SIZE
                col = idx % KERNEL_SIZE
                binary = int_to_twos_complement( int(value), bits )
                f.write( f"{idx}\t{row}\t{col}\t{int(value)}\t{binary}\n" )

        elif parameter_type == "dense":
          f.write("Index\tFeatureMap\tPixel\tDecimal\tBinary\n")
          f.write("-" * 80 + "\n")

          pixels_per_map = POOL_OUTPUT_SIZE * POOL_OUTPUT_SIZE

          for idx, value in enumerate(values):
              fmap = idx // pixels_per_map
              pixel = idx % pixels_per_map
              binary = int_to_twos_complement( int(value), bits )
              f.write( f"{idx}\t{fmap}\t{pixel}\t{int(value)}\t{binary}\n" )

        elif parameter_type == "bias":
            f.write( "Index\tDecimal\tBinary\n" )
            f.write( "-"*40 + "\n" )

            for idx, value in enumerate(values):
                binary = int_to_twos_complement( int(value), bits )
                f.write( f"{idx}\t{int(value)}\t{binary}\n" )
        else:
            f.write( "Index\tDecimal\tBinary\n" )
            f.write( "-"*40 + "\n" )

            for idx, value in enumerate(values):
                binary = int_to_twos_complement( int(value), bits )
                f.write( f"{idx}\t{int(value)}\t{binary}\n" )

def export_image_mem(filename, image):
    export_image( image, filename )

# Parameter Export

def export_kernel(folder, kernel):
    export_decimal( folder / "weights_decimal.txt", kernel )

    export_binary(  folder / "weights_binary.mem", kernel,
        hardware["format"]["weight_bits"] )

    export_indexed_parameters( folder / "weights_indexed.txt",
        kernel, hardware["format"]["weight_bits"],
        parameter_type="kernel" )

def export_bias(folder, bias):

    export_decimal( folder / "bias_decimal.txt", [bias] )

    export_binary( folder / "bias_binary.mem", [bias],
        hardware["format"]["bias_bits"] )

    export_indexed_parameters( folder / "bias_indexed.txt",
        [bias], hardware["format"]["bias_bits"],
        parameter_type="bias" )

def export_dense_weights(folder, weights):

    export_decimal( folder / "weights_decimal.txt", weights )

    export_binary( folder / "weights_binary.mem",
        weights, hardware["format"]["weight_bits"] )

    export_indexed_parameters( folder / "weights_indexed.txt", weights,
        hardware["format"]["weight_bits"], parameter_type="dense" )

# Feature Map Export

def export_conv_map(folder, fmap):
    export_binary( folder/"expected_conv.mem", fmap,
        hardware["format"]["conv_bits"] )

def export_relu_map(folder, fmap):
    export_binary( folder/"expected_relu.mem", fmap,
        hardware["format"]["conv_bits"] )

def export_pool_map(folder, fmap):
    export_binary( folder/"expected_pool.mem", fmap,
        hardware["format"]["conv_bits"] )

def export_flatten(filename, vector):
    export_binary( filename, vector, hardware["format"]["conv_bits"] )

def export_neuron(folder, value):
    export_binary( folder/"expected_neuron.mem", [value],
        hardware["format"]["neuron_bits"] )

# Manifest Utilities

def write_header(file):
    file.write("Hardware Verification Package\n")
    file.write("="*60)
    file.write("\n\n")

def write_network_summary(file):
    net = hardware["network"]

    file.write("Network Configuration\n")
    file.write("------------------------------\n")

    file.write(f"Image Size      : {net['image_size']}\n")
    file.write(f"Conv Size       : {net['conv_size']}\n")
    file.write(f"Pool Size       : {net['pool_size']}\n")
    file.write(f"Flatten Length  : {net['flatten_size']}\n")
    file.write(f"Classes         : {net['classes']}\n\n")


def write_fixed_point_summary(file):
    fmt = hardware["format"]

    file.write("Fixed Point Formats\n")
    file.write("------------------------------\n")

    file.write(f"Pixel Bits      : {fmt['pixel_bits']}\n")
    file.write(f"Weight Bits     : {fmt['weight_bits']}\n")
    file.write(f"Weight Fraction : {fmt['weight_frac']}\n")
    file.write(f"Bias Bits       : {fmt['bias_bits']}\n")
    file.write(f"Bias Fraction   : {fmt['bias_frac']}\n")
    file.write(f"Conv Bits       : {fmt['conv_bits']}\n")
    file.write(f"Neuron Bits     : {fmt['neuron_bits']}\n\n")


def export_manifest( filename, image_index,
        label, prediction, neuron_outputs):

    with open(filename, "w") as f:
        write_header(f)

        f.write(f"Dataset Index : {image_index}\n")
        f.write(f"Ground Truth  : {label}\n")
        f.write(f"Prediction    : {prediction}\n\n")

        write_network_summary(f)
        write_fixed_point_summary(f)

        f.write("Neuron Outputs\n")
        f.write("------------------------------\n")

        for i, value in enumerate(neuron_outputs):
            f.write( f"Neuron {i:2d} : {value}\n" )

# Overflow Report

def export_overflow_report(folder):
    report = folder/"overflow_report.txt"

    with open(report, "w") as f:
        f.write("Overflow Report\n")
        f.write("="*50)
        f.write("\n\n")

        f.write( "All exported values are assumed\n" )

        f.write( "to already be checked during\n" )

        f.write( "quantization.\n" )


print("\nCore export utilities loaded successfully.")

# Convolution Channel Export
def export_conv_parameters(folder, channel):
    create_folder(folder)

    kernel = hardware["conv"]["weights_int"][:, :, 0, channel]
    bias = hardware["conv"]["bias_int"][channel]

    export_kernel(folder, kernel)
    export_bias(folder, bias)

# Dense Neuron Export
def export_dense_parameters(folder, neuron):
    create_folder(folder)

    weights = hardware["dense"]["weights_int"][:, neuron]
    bias = hardware["dense"]["bias_int"][neuron]

    export_dense_weights(folder, weights)
    export_bias(folder, bias)

# Define Feature maps export
def export_feature_maps(folder, results):
    create_folder(folder)

    for channel in range(NUM_FILTERS):
        export_binary( folder / f"conv{channel}_expected.mem",
            results["conv"][channel], hardware["format"]["conv_bits"] )

        export_binary( folder / f"relu{channel}_expected.mem",
            results["relu"][channel], hardware["format"]["conv_bits"] )

        export_binary( folder / f"pool{channel}_expected.mem",
            results["pool"][channel], hardware["format"]["conv_bits"] )

# Define Neuro Output export
def export_neuron_outputs(folder, results):
    create_folder(folder)

    for neuron in range(NUM_CLASSES):
        export_binary( folder / f"neuron{neuron}_expected.mem",
            [results["neurons"][neuron]], hardware["format"]["neuron_bits"] )

# Flatten Export
def export_flatten_vector(folder, results):
    export_flatten( folder / "flatten.mem", results["flatten"] )

# Complete Network Parameter Export
def export_network_parameters(folder):

    create_folder(folder)

    for channel in range(NUM_FILTERS):
        export_conv_parameters( folder / f"conv_{channel}", channel )

    for neuron in range(NUM_CLASSES):

        export_dense_parameters( folder / f"neuron_{neuron}", neuron )

# Complete Image Export
def export_image_package( folder, image_index, label, results ):
    create_folder(folder)

    export_image_mem( folder / "image.mem", results["image"] )

    export_flatten( folder / "flatten.mem", results["flatten"] )

    export_feature_maps( folder, results )

    export_neuron_outputs( folder, results )

    export_manifest( folder / "verification_manifest.txt",
        image_index, label,
        results["prediction"],
        results["neurons"] )

    export_overflow_report(folder)

# Archive Utility
def create_zip_archive(folder, archive_name):

    shutil.make_archive( archive_name, "zip", folder )


# Package Summary
def print_package_summary(folder):
    print("\n")
    print("=" * 60)
    print("Package Generated")
    print("=" * 60)
    print(f"Location : {folder}")
    print("=" * 60)

print("\nHigh-level export manager ready.")



"""**Cell 8A:** Export Parameters"""

print("Generating Hardware Verification Package")

# User Configuration
VERIFY_IMAGE_INDEX = 0          # Image used for HDL verification
IMAGES_PER_CLASS = 5            # Used later in Part B

# Folder Layout
PARAMETER_FOLDER = EXPORT_ROOT / "parameters"
VERIFY_FOLDER = EXPORT_ROOT / "verification"

create_clean_folder(EXPORT_ROOT)
create_folder(PARAMETER_FOLDER)
create_folder(VERIFY_FOLDER)
create_clean_folder(TEST_IMAGE_ROOT)

# Export Network Parameters (Only Once)
print("\nExporting CNN parameters...")
export_network_parameters(PARAMETER_FOLDER)
print("Done.")

# Generate Single Verification Image
print("\nGenerating verification image...")
verification_results = emulate_complete_pipeline( x_test[VERIFY_IMAGE_INDEX] )
verification_label = int(y_test[VERIFY_IMAGE_INDEX])

export_image_package( folder=VERIFY_FOLDER, image_index=VERIFY_IMAGE_INDEX, label=verification_label, results=verification_results )
print("Done.")

# Verification Summary
print("\nVerification Image")

print(f"Dataset Index : {VERIFY_IMAGE_INDEX}")
print(f"Ground Truth  : {verification_label}")
print(f"Prediction    : {verification_results['prediction']}")

print("\nNeuron Outputs")

for neuron, value in enumerate(verification_results["neurons"]):
    print(f"Neuron {neuron}: {value}")

# Parameter Summary

print("\nParameter Summary")

print("Convolution")

for channel in range(NUM_FILTERS):
    kernel = hardware["conv"]["weights_int"][:, :, 0, channel]
    print( f"Kernel {channel} : "
        f"{kernel.shape[0]}x{kernel.shape[1]}" )

print("Dense")
print( f"Inputs  : {hardware['dense']['inputs']}" )
print( f"Outputs : {hardware['dense']['outputs']}" )

# Export Parameter Statistics

with open(PARAMETER_FOLDER / "parameter_statistics.txt", "w") as f:
    f.write("CNN Parameter Summary\n")
    f.write("=" * 50 + "\n\n")

    f.write("Convolution\n")
    f.write("-------------------------\n")

    f.write( f"Filters       : {NUM_FILTERS}\n" )

    f.write( f"Kernel Size   : {KERNEL_SIZE}\n\n" )

    f.write("Dense Layer\n")
    f.write("-------------------------\n")

    f.write( f"Inputs        : {FC_INPUTS}\n" )

    f.write( f"Outputs       : {NUM_CLASSES}\n\n" )

    f.write("Fixed Point\n")
    f.write("-------------------------\n")

    f.write( f"Weight Format : "
        f"Q{WEIGHT_INT_BITS}.{WEIGHT_FRAC_BITS}\n" )

    f.write( f"Bias Format   : "
        f"Q{BIAS_INT_BITS}.{BIAS_FRAC_BITS}\n" )

    f.write( f"Conv Bits     : "
        f"{CONV_OUTPUT_BITS}\n" )

    f.write( f"Neuron Bits   : "
        f"{NEURON_OUTPUT_BITS}\n" )

print("\nParameter statistics exported.")

# Status

print("\n" + "=" * 60)
print("Part A Complete")
print("=" * 60)

print("Generated:")

print("✓ Parameter Package")
print("✓ Verification Package")
print("✓ Test Archive Folder")

print("\nReady for Part B...")



"""**CELL 8B:** Export Test Image Archive"""

print("\nGenerating Multi-Image Verification Archive")

total_images = 0

# Generate Verification Images
for target_class in range(NUM_CLASSES):

    print(f"\nClass {target_class}")

    class_indices = np.where(y_test == target_class)[0]

    if len(class_indices) == 0:
        print("  No samples found.")
        continue

    selected_indices = class_indices[:IMAGES_PER_CLASS]

    for class_image_number, dataset_index in enumerate(selected_indices):
        results = emulate_complete_pipeline( x_test[dataset_index] )

        folder = ( TEST_IMAGE_ROOT / f"class_{target_class}" /
            f"img_{class_image_number:03d}" )

        export_image_package( folder=folder,
            image_index=int(dataset_index),
            label=int(target_class), results=results )

        total_images += 1

    print( f"  Exported {len(selected_indices)} image(s)" )

# Zip Packages
print("\nCreating ZIP archives...")
create_zip_archive( EXPORT_ROOT, "hardware_verification_files" )
create_zip_archive( TEST_IMAGE_ROOT, "test_images_archive" )
print("Done.")

# Final Summary
print("\n" + "=" * 60)
print("Export Summary")
print("=" * 60)

print(f"Verification Image Index : {VERIFY_IMAGE_INDEX}")
print(f"Verification Label       : {verification_label}")
print(f"Verification Prediction  : {verification_results['prediction']}")

print()

print(f"Images per Class         : {IMAGES_PER_CLASS}")
print(f"Classes                  : {NUM_CLASSES}")
print(f"Total Images Exported    : {total_images}")

print()

print("Generated Packages")

print("------------------------------")

print("hardware_verification_files/")
print("hardware_verification_files.zip")

print()

print("test_images_archive/")
print("test_images_archive.zip")

print("\nExport completed successfully.")